name: app
description: app module.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
