name: logger
description: logger module.
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0

dev_dependencies:
  test: ^1.26.3
  very_good_analysis: ^10.0.0
