name: logger
description: logger module.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.3
