name: url_strategy
description: url_strategy module.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
