name: l10n
description: l10n module.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  slang_flutter: ^4.11.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  slang_build_runner: ^4.11.0
  test: ^1.26.3
