name: game
description: game module.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  audioplayers: 6.5.1
  bonfire: ^4.0.0-beta.2
  bot_toast: ^4.1.3
  flame_audio: ^2.11.13
  flame_splash_screen: ^0.3.1+2
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  games_services: ^5.0.0
  gap: ^3.0.1
  group_button: ^5.3.4
  nb_utils: ^7.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  tray_manager: ^0.5.2

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/images/emote/
    - assets/images/npc/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/imp/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/boss/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Normal
      fonts:
        - asset: fonts/font_pixel.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
